name: mon_flux_rss
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.2.beta
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webfeed: ^0.7.0
  http: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
